### ISSUE TITLE
User story First overview #1

### ISSUE THREAD

**Issue by magjo21** [magjo21/capstone-project#1]
# Capstone-project-EasyRev
---
### Value Proposition

**As a** User,

**I want to** be able to give a quick review,

**so that** I can go on details reviews.

### Description

> 💡 Only create the frontend from static data here

![image](https://user-images.githubusercontent.com/117904136/213429889-703bc792-c63d-4ced-b909-4b2f94b7186f.png)

>  💡 Details Page

![image](https://user-images.githubusercontent.com/117904136/213662231-e8f8d190-c817-4708-b2ab-0d552cbf30a3.png)

### Acceptance Criteria

- [ ] On the main page there are 3 buttons done as smileys.
- [ ] The 3 smileys take you to one page each. The green one if your review is good. The yellow-orange one if your review is medium. The red one if your review is bad.
- [ ] the page you get to, depending on which smiley you click, is the detailed questions page.
On this page are specific questions about the restaurant you want to review. Friendliness, cleanliness, taste, quantity, quality, ambience.

### Tasks

- [ ] Create Headline and Buttons
- [ ] Create detailed page 
- [ ] Create a card component displaying the required elements

**Comment by AstridOttmann** [comment]
it becomes not quite clear, if you also implement the link? Maybe you can add this by tasks?

**Comment by ThomasF85** [comment]
Your acceptance criteria state: - Create detailed questions
This is a problem, since you should then also provide the information what the detailed question would be and what the detailed question page looks like.
You have two options:
1. Your story does not say - Create detailed questions, and it should say - If a smiley is clicked, the user gets to an empty dummy page
2. You have to specify what the details page looks like and what the detail questions are

**Comment by ThomasF85** [comment]
The story and acceptance criteria should be written, so that you can give the story to another developer and they know exactly what to implement. If another developer reads your acceptance criteria, they do not know what exactly to implement.
There are a lot of open questions, for example:
- What are the six buttons on the details page?
- What happens when I click the buttons on the details page?
- What questions and in what form should I put on the details page?
- What happens when I click the submit button on the details page?

Please either specify your story so that all these questions are answered (which would be best done if you include a picture / excalidraw of the details page) or cut your story smaller, so it does not contain a details page with content.

**Comment by ThomasF85** [comment]
Again, if the details page is a part of your user story, please provide a wireframe and a detailed description.

**Comment by ThomasF85** [comment]
Looks good, just one thing you should change:
If the submit button on the detailed page does not do anything, remove it. We do not want any interactive elements without functionality in the app.

**Comment by ThomasF85** [comment]
Looks good!
