### ISSUE TITLE
Login/Page

### ISSUE THREAD

**Issue by magjo21** [magjo21/capstone-project#10]
## Value Proposition

**As a**Costumer
**I want to** have a login  
**so that** my collected data is save  
​

## Description

![image](https://user-images.githubusercontent.com/117904136/214307916-abb622e3-c64f-4fe7-a263-8699ee2baad4.png)
​

## Acceptance Criteria

- [ ] contains a Headline "Login"
- [ ] the login side has input field were i can put in my Passwort
- [ ] the password is Hardcoded
- [ ] the side has a submit button were the i can enter the Passwort 
- [ ] it contains a button that leads me back to the index.js

## Tasks

- [ ] create a Headline
- [ ] create a Login input field
- [ ] create a submit button 
- [ ] create a button that leads navigates back to the index.js

## Complexity

M
