### ISSUE TITLE
Review site/ submit button #2

### ISSUE THREAD

**Issue by magjo21** [magjo21/capstone-project#2]
## Value Proposition

**As a** User,
**I want to** submit my review  
**so that** the restaurant gets the review.
​

## Description

![image](https://user-images.githubusercontent.com/117904136/213670618-7c4dcaac-fe31-4413-a102-d689d137094c.png)
​

## Acceptance Criteria

- [ ] If the user is finished with his review, he presses the Submit button.
- [ ] The Submit button saves the data local.​

## Tasks

- [ ] Create a submit button
- [ ] The submit should save the data local 
​

## Complexity

...(L)

**Comment by ThomasF85** [comment]
Nice and well defined user story!

One thing you should change: You are writing "As a user...", but you have different personas (e.g. customer, restaurant manager, ...). Please write your user story from the point of view of one of these personas. Here you could write:
As a customer I want to submit my feedback so that the restaurant can use it to improve.

**Comment by ThomasF85** [comment]
Looks good!
