### ISSUE TITLE
Dynamic Review page

### ISSUE THREAD

**Issue by magjo21** [magjo21/capstone-project#20]
## Value Proposition

**As a** Author
**I want to** a dynamic page 
**so that** i dont have the review page 3 times in the code 
​

## Description

>The 3 pages should be one dynamic page

![image](https://user-images.githubusercontent.com/117904136/217298117-51972dce-4a56-4a44-9da6-4866857b25f4.png)​

## Acceptance Criteria

- [ ] it should contain dynamic routing
- [ ] the pages should have different headlines
- [ ] the values from the page should end up in the overview in the correct category      ​

## Tasks

- [ ] create dynamic routing 
- [ ] create different Headlines

      ​

## Complexity

L

**Comment by Long-HaHoang** [comment]
Hi Magnus,

> As a Author
I want to a dynamic page
so that i dont have the review page 3 times in the code

I don't understand the author's part. Do mean the customer, the restaurant owner, or yourself the developer?
The author has a broader meaning. E.g. a user is technically an author, too. Since the user creates a vote.

Besides that, there are some typos in the value proposition.

> As a **Developer** ( I assume that's what you meant)
I want to **have** a dynamic page for the voting
so that **I don't** have to review three different pages.

This will make it clearer what you want and what your goal is with this user story.

**Comment by magjo21** [comment]
> Hi Magnus,
> 
> > As a Author
> > I want to a dynamic page
> > so that i dont have the review page 3 times in the code
> 
> I don't understand the author's part. Do mean the customer, the restaurant owner, or yourself the developer? The author has a broader meaning. E.g. a user is technically an author, too. Since the user creates a vote.
> 
> Besides that, there are some typos in the value proposition.
> 
> > As a **Developer** ( I assume that's what you meant)
> > I want to **have** a dynamic page for the voting
> > so that **I don't** have to review three different pages.
> 
> This will make it clearer what you want and what your goal is with this user story.

Hi Long,

Yes that's what I meant, I will quickly change that thank you

**Comment by Long-HaHoang** [comment]
Hi Magnus,

in your criteria you also mention an `it`, can you be clearer about what do mean by it?
Did mean the voting page or the app itself?

Besides that it's ok.
You can modify it a bit and repost it on slack and you should be good to go. 👍

**Comment by magjo21** [comment]
> Hi Magnus,
> 
> in your criteria you also mention an `it`, can you be clearer about what do mean by it? Did mean the voting page or the app itself?
> 
> Besides that it's ok. You can modify it a bit and repost it on slack and you should be good to go. 👍

Sounds good thank you!!

**Comment by Olga-Mishareva** [comment]
Looks gut to me :)
