### ISSUE TITLE
Percent textfield

### ISSUE THREAD

**Issue by magjo21** [magjo21/capstone-project#21]
## Value Proposition

**As a** User
**I want to** have the results in percent
**so that** so that I can judge the results faster

## Description

>Percent next to the Smiley category 
![image](https://user-images.githubusercontent.com/117904136/217489968-30022bec-e017-458c-8346-e2616317f8e9.png)​

## Acceptance Criteria

- [ ] it should contain a textfield 
- [ ] in the textfield the percentages are displayed​

## Tasks

- [ ] create a textfield 
- [ ] create a variable that converts the evaluation into percentages
​

## Complexity

S

**Comment by marcterre** [comment]
Hey Magnus, in your acceptance criteria you write "it should contain a textfield", i dont know what "it" means. Maybe write something like: "There is a textfield next to the emojis which displays the corresponding results in percentage".
The rest lgtm 🙂

**Comment by magjo21** [comment]
> Hey Magnus, in your acceptance criteria you write "it should contain a textfield", i dont know what "it" means. Maybe write something like: "There is a textfield next to the emojis which displays the corresponding results in percentage". The rest lgtm 🙂

hi thank you. i change this quickly

**Comment by Olga-Mishareva** [comment]
Hi Magnus, 
LGTM
