### ISSUE TITLE
Local storage

### ISSUE THREAD

**Issue by magjo21** [magjo21/capstone-project#24]
## Value Proposition

**As a** User
**I want to** be able to save data
**so that** my data is saved 
​

## Acceptance Criteria

- [ ] the side should work the same as before
- [ ] the data should be stored in local Storage

## Tasks

- [ ] implement local storage for "reviews"
- [ ] load the local storage  if available 
- [ ] if no local storage is available, set the local storage

## Complexity

L

**Comment by shyamtawli** [comment]
Hey can I try my hands on it?

**Comment by magjo21** [comment]
> Hey can I try my hands on it?

Yes, sure!

**Comment by shyamtawli** [comment]
Okay will try asap to solve it, please assign me.

**Comment by magjo21** [comment]
sorry, Its a i asked my coach and i have to do it by my own.

**Comment by magjo21** [comment]
> sorry, Its a i asked my coach and i have to do it by my own.

Thanks anyway

**Comment by Long-HaHoang** [comment]
Hi Magnus,
I just saw you are using jotai.
You could look into the Zustand workshop video, not for the zustand but for the use-local-storeage custom hook.
Coach Felix mentioned something about some error at the end of the video.
Next.js doesn't like local-storage you might end up with a hydration error, maybe.
Most of us in the group are using local storage, you might want to take a look at their code. 

Anyway happy coding 👍
