### ISSUE TITLE
Homepage styling

### ISSUE THREAD

**Issue by magjo21** [magjo21/capstone-project#27]
## Value Proposition

**As a** User
**I want to** have a better
**so that** it's easier to understand the app.
​

## Description

![image](https://user-images.githubusercontent.com/117904136/218493200-f48b6ac7-32ae-4f78-99b7-b416fd86f8e0.png)
​

## Acceptance Criteria

- [ ] display 3 buttons
- [ ] display A headline

## Tasks

- [ ] add styling to the Homepage
- [ ] add global backgroundstyling
- [ ] add styling on the three buttons

## Complexity

M

**Comment by Diren-T** [comment]
looks good!
