### ISSUE TITLE
Reviewpage styling

### ISSUE THREAD

**Issue by magjo21** [magjo21/capstone-project#28]
## Value Proposition

**As a** User
**I want to** have a better
**so that** it's easier to understand the app.
​

## Description

![image](https://user-images.githubusercontent.com/117904136/218682923-5d7f2244-b64f-47a3-9e50-f6a440273dee.png)​

## Acceptance Criteria

- [ ] display 6 checkboxes
- [ ] display a dynamic headline
- [ ] display the submit button

## Tasks

- [ ] add styling to the review page
- [ ] add styling to the checkboxes
- [ ] add styling to the submit button

## Complexity

M

**Comment by RobinWitt** [comment]
"As a User, I want to have a better .... so that it's easier to understand the app."
Looks like you lost some words there.
