### ISSUE TITLE
Greeting page styling

### ISSUE THREAD

**Issue by magjo21** [magjo21/capstone-project#29]
## Value Proposition

**As a** User
**I want to** have a better styling
**so that** it's easier to understand the app.
​

## Description

![image](https://user-images.githubusercontent.com/117904136/218696629-bb34ba49-1724-4075-a850-85a35d2d2816.png)

## Acceptance Criteria

- [ ] display Headline
- [ ] display button which leads back to the homepage

## Tasks

- [ ] add styling to the greetings page
- [ ] add styling to the Headline
- [ ] add styling to the button

## Complexity

M

**Comment by RobinWitt** [comment]
Don't forget to write "your feedback" instead of "you're feedback" in your actual code. ;)
Looks good to me!
