### ISSUE TITLE
User credits 

### ISSUE THREAD

**Issue by magjo21** [magjo21/capstone-project#3]
## Value Proposition

**As a** user
**I want to** have credits for my feedback
**so that** im coming back 
​

## Description

![image](https://user-images.githubusercontent.com/117904136/213682700-2211a643-69c9-404b-ac6a-774e747732bd.png)

​

## Acceptance Criteria

- [ ] This side ist the last one for the user
- [ ] The page shows to headlines. One for a Thank you and one for a pleas come back.
- [ ] It also has a space for an img or an QR-Code
      ​

## Tasks

- [ ] Create Headlines.
- [ ] create an image spaceholder .      ​

## Complexity

S

**Comment by RobinWitt** [comment]
Hi Magnus, you should clarify that you add a new page (in your tasks) and how this page is reached.
The complexity of the user story feels good to me.

**Comment by AGeck113** [comment]
Looks really good!
