### ISSUE TITLE
overviewpage styling

### ISSUE THREAD

**Issue by magjo21** [magjo21/capstone-project#30]
## Value Proposition

**As a** User
**I want to** have a better styling
**so that** it's easier to understand the app.
​

## Description

![image](https://user-images.githubusercontent.com/117904136/218698298-d8af638a-2787-4490-9c34-37dfecee919e.png)

## Acceptance Criteria

- [ ] display Headline
- [ ] display button with more details
- [ ] display the 3 emoji’s 

## Tasks

- [ ] add styling to the overview page
- [ ] add styling to the Headline
- [ ] add styling to the buttons

## Complexity

M
