### ISSUE TITLE
Details page styling

### ISSUE THREAD

**Issue by magjo21** [magjo21/capstone-project#31]
## Value Proposition

**As a** User
**I want to** have a better styling
**so that** it's easier to understand the app.
​

## Description

![image](https://user-images.githubusercontent.com/117904136/218700233-78d977ea-f4e9-45bf-bd3b-0196ad9b9ced.png)

## Acceptance Criteria

- [ ] display Headline
- [ ] display details 
- [ ] display go back button

## Tasks

- [ ] add styling to the Details page
- [ ] add styling to the button
- [ ] add styling to the details

## Complexity

M
