### ISSUE TITLE
Menu/Overview

### ISSUE THREAD

**Issue by magjo21** [magjo21/capstone-project#4]
## Value Proposition

**As a** Restaurant
**I want to** be able to overview 
**so that** i can see all reviews
​

## Description

![image](https://user-images.githubusercontent.com/117904136/213688357-aa060214-3733-4368-ab6e-c34361534964.png)​

## Acceptance Criteria

- [ ] On the main Page there is a Menu Button.
- [ ] The Menu Button navigates me to a _Overview.js_
- [ ] The _Overview.js_ is a page where i have a Quick overlook on the three clicked smileys

## Tasks

- [ ] Create a Menu Button.
- [ ] Create Overview.js
- [ ] Create the three smileys.      ​

## Complexity

... (T-Shirt Sizes XS to XL)

**Comment by TariqAlQadi** [comment]
Hi Magnus,
I would like to see what the overview would look like and it is not clear to me what kind of elements  the smileys are!
But the rest looks good to me!
