### ISSUE TITLE
Show details site

### ISSUE THREAD

**Issue by magjo21** [magjo21/capstone-project#5]
## Value Proposition

**As a** user
**I want to** have credits for my feedback
**so that** im coming back 
​

## Description

> Wireframe
![image](https://user-images.githubusercontent.com/117904136/213708720-ea6f1544-f0b7-4f47-8757-b0131de9263b.png)
## Acceptance Criteria

- [ ] If the restaurant wants more information about the button that was the most popular, they can click on the show details button and go to the page for that button
- [ ] on the detail.js site the restaurant will find information for each button
- [ ] It also has a space for an img or an QR-Code
      ​

## Tasks

- [ ] Create "Show Details" button
- [ ] Create detail.js   
- [ ] Create Headline
- [ ] Create Button that clicked most  
   ​

## Complexity

M

**Comment by AGeck113** [comment]
Hi Magnus, 
Can you make clear what "Create Button that clicked most" is? is it a component?
if yes, then you can write something like that:
- Display all buttons
- create button component
- each button is displayed by an button component
You could also be a bit more specific like  
- Create "Show Details" button, that links to the details.js(for example)

**Comment by NikRoe** [comment]
Hi Magnus,

a promising start!

Some notes:

- You should leave out `It also has a space for an img or an QR-Code` from your acceptance criteria. This seems to relate to a yet upcoming user story and we only want to implement in a user story what is needed for that very user story. 

- Will the detail pages be dynamically rendered ([detail].js) or will there be a static page for each of the 3 options? 

- Semantically you should use the `Link` component from Next.js to navigate to another page. You can style it to appear like a button

- Will there be an option to navigate back to the overview page from the detail pages? If so, please show this on your wireframes and mention it in your user story
