### ISSUE TITLE
Thank You side

### ISSUE THREAD

**Issue by magjo21** [magjo21/capstone-project#8]
## Value Proposition

**As a** User  
**I want to** get a thank you 
**so that** im coming back and feel well
​

## Description
>Wireframe 
![image](https://user-images.githubusercontent.com/117904136/214282845-626d5a82-3fbd-43b6-b43e-d1e227119dd8.png)​

## Acceptance Criteria

- [ ] a greetings message 
- [ ] there is an icon 
- [ ] there is a good bye massage     ​

## Tasks

- [ ] create a headline
- [ ] create an icon
- [ ] create a goodbye message

## Complexity

S

**Comment by Diren-T** [comment]
looks good 👍
